const ERROR_MESSAGES = {
  INVALID_NOTIFICATION_CREDENTIALS: 'InvalidCredentials',
  NOTIFICATION_PAYLOAD_TOO_LARGE: 'MessageTooBig',
  NOTIFICATION_RATE_EXCEEDED: 'MessageRateExceeded',
  DEVICE_NOT_REGISTERED: 'DeviceNotRegistered',
  PUSH_NOTIFICATION_ERROR: 'error',
};

const VALUES = {
  NOTIFICATIONS_CHANNEL: '@EXPO_NOTIFICATIONS-APP',
};

export default {
  ERROR_MESSAGES,
  VALUES,
};
